---
output: 
  pdf_document:
    extra_dependencies:
      amsmath 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      error = FALSE,
                      fig.pos = "H")
```

## Models for testing positive investigation  

Let  
$OP_i$ be the odds of testing positive for SARS-CoV2 in Orange County.  
$\overrightarrow{\beta}_{\text{Age Group}} = (\beta_{\text{Age[5-9]}}, \beta_{\text{Age[10-14]}}, \beta_{\text{Age[15-19]}}, \beta_{\text{Age[20-24]}}, \beta_{\text{Age[25-29]}}, \beta_{\text{Age[30-34]}}, \beta_{\text{Age[35-39]}}\\ \beta_{\text{Age[40-49]}},  \beta_{\text{Age[50-59]}}, \beta_{\text{Age[60-69]}}, \beta_{\text{Age[70-79]}}, \beta_{\text{Age[80+]}})$  
$\overrightarrow{\beta}_{\text{Race}} = (\beta_{\text{Asian}}, \beta_{\text{Black}}, \beta_{\text{Hispanic}}, \beta_{\text{NativeAmerican}}, \beta_{\text{PacificIslander}}, \beta_{\text{OtherRace}}, \beta_{\text{Unknown}})$  
$\overrightarrow{\beta}_{\text{College}} = (\beta_{\text{\% with College Degree Quartile 2}}, \beta_{\text{\% with College Degree Quartile 3}}, \beta_{\text{\% with College Degree Quartile 4}})$  
$\overrightarrow{\beta}_{\text{Insurance}} = (\beta_{\text{\% with Insurance Quartile 2}}, \beta_{\text{\% with Insurance Quartile 3}}, \beta_{\text{\% with Insurance Quartile 4}})$

For clarity the base terms ($\text{BaseTerms}_i$) are defined to be the terms present in all models:
\begin{equation*}
\label{eq:BaseTermsOP}
	\begin{split}
		\text{BaseTerms}_i =& \beta_0 + \overrightarrow{\beta}_{\text{Age Group}}\overrightarrow{\text{Age Group}}_i + \beta_{\text{Sex}}\text{Sex}_i + \overrightarrow{\beta}_{\text{Race}}\overrightarrow{\text{Race}}_i\\
		&+ \overrightarrow{\beta}_{\text{College}}\overrightarrow{\text{\% with College Degree Quartile}}_i\\
		&+ \overrightarrow{\beta}_{\text{Insurance}}\overrightarrow{\text{\% with Medical Insurance Quartile}}_i \\
		&+ \beta_{\text{Population Density}}\text{Population Density}_i + \beta_{\text{Median Income}}\text{Median Income}_i
	\end{split}
\end{equation*}

Model 1:
\begin{equation}
\label{eq:Model1OM}
	\begin{split}
		\log(OP_i) &= \text{BaseTerms}_i\\ 
		&+ \beta_{\text{Time}}\text{Time}_i,
	\end{split}
\end{equation}
with a random intercept for zip code.

Model 2:
\begin{equation}
\label{eq:Model2OM}
	\begin{split}
		\log(O_i) &= \text{BaseTerms}_i\\ 
		&+ \beta_{\text{Time}}\text{Time}_i + \beta_{\text{Time2}}\text{Time}^2_i,
	\end{split}
\end{equation}
with a random intercept for zip code.

Model 3:
\begin{equation}
\label{eq:Model3OM}
	\begin{split}
		\log(OP_i) &= \text{BaseTerms}_i\\ 
		&+ \beta_{\text{Time}}\text{Time}_i + \beta_{\text{Time2}}\text{Time}^2_i, \\
		&+ \beta_{\text{Interaction1}}\text{Median Income}_i\times\text{Time}_i + \beta_{\text{Interaction2}}\text{Median Income}_i\times\text{Time}^2_i,
	\end{split}
\end{equation}
with a random intercept for zip code.

Model 4:  
Generalized additive model
\begin{equation}
\label{eq:Model4OM}
	\begin{split}
		\log(OP_i) &= \text{BaseTerms}_i\\ 
		&+ \beta_{\text{Time}}f(\text{Time}_i),
	\end{split}
\end{equation}
with a random intercept for zip code.

Model 5:  
Generalized additive model
\begin{equation}
	\label{eq:Model5OM}
		\begin{split}
		\log(OP_i) &= \text{BaseTerms}_i\\ 
		&+ \beta_{\text{Time}}f(\text{Time}_i) + \beta_{\text{Interaction}}\text{Median Income}_i\times f(\text{Time}_i),
	\end{split}
\end{equation}
with a random intercept for zip code.

Model 6:  
Generalized additive model
\begin{equation}
	\label{eq:Model6OM}
		\begin{split}
		\log(OP_i) &= \text{BaseTerms}_i\\ 
		&+ \beta_{\text{Time}}f(\text{Time}_i) + \beta_{\text{Interaction}}\text{Median Income}_i\times f(\text{Time}_i),
	\end{split}
\end{equation}
without a random intercept for zip code.


\newpage
# Models for mortality investigation  
Let  
$OM_{i}$ be the odds of mortality among individuals who tested positive for SARS-CoV2 in Orange County.  
$\overrightarrow{\beta}_{\text{Race}} = (\beta_{\text{Asian}}, \beta_{\text{Black}}, \beta_{\text{Hispanic}}, \beta_{\text{Native American}}, \beta_{\text{Pacific Islander}}, \beta_{\text{Other Race}}, \beta_{\text{Unknown}})$  
$\overrightarrow{\beta}_{\text{College}} = (\beta_{\text{\% with College Degree Quartile 2}}, \beta_{\text{\% with College Degree Quartile 3}}, \beta_{\text{\% with College Degree Quartile 4}})$  
$\overrightarrow{\beta}_{\text{Insurance}} = (\beta_{\text{\% with Insurance Quartile 2}}, \beta_{\text{\% with Insurance Quartile 3}}, \beta_{\text{\% with Insurance Quartile 4}})$.

For clarity the base terms ($\text{BaseTerms}_i$) are defined to be the terms present in all models:  
\begin{equation*}
  \label{eq:BaseTermsOM}
  \begin{split}
    \text{BaseTerms}_i &= \beta_0 + \beta_{\text{Age}}\text{Age}_i + \beta_{\text{Sex}}\text{Sex}_i + \overrightarrow{\beta}_{\text{Race}}\overrightarrow{\text{Race}}_i\\
		&+ \overrightarrow{\beta}_{\text{College}}\overrightarrow{\text{\% with College Degree Quartile}}_i\\
		&+ \overrightarrow{\beta}_{\text{Insurance}}\overrightarrow{\text{\% with Medical Insurance Quartile}}_i \\
		&+ \beta_{\text{Population Density}}\text{Population Density}_i + \beta_{\text{Median Income}}\text{Median Income}_i\\ 
		&+ \beta_{\text{Time}}\text{Time}_i\\
		&+ \beta_{\text{\% Hospital Beds Available}}\text{\% Hospital Beds Available}_i,
  \end{split}
\end{equation*}

Model 0:
\begin{equation}
  \label{eq:Model0OM}
  \begin{split}
    \log(OM_i) &= \text{BaseTerms}_i
  \end{split}
\end{equation}
without a random intercept for zip code.

Model 1:
\begin{equation}
  \label{eq:Model1OM}
  \begin{split}
    \log(OM_i) &= \text{BaseTerms}_i,
  \end{split}
\end{equation}
with a random intercept for zip code.


\newpage
# Models for testing seropositive investigation  
Let  
$OSP_i$ be the odds of testing positive for COVID-19 in Orange County.  
$\overrightarrow{\beta}_{\text{Age Group}} = (\beta_{\text{Age[18-24]}}, \beta_{\text{Age[25-29]}}, \beta_{\text{Age[30-34]}}, \beta_{\text{Age[35-39]}}, \beta_{\text{Age[40-44]}}, \beta_{\text{Age[45-49]}}, \beta_{\text{Age[50-54]}}, \\ \beta_{\text{Age[55-59]}}, \beta_{\text{Age[60-64]}}, \beta_{\text{Age[65-69]}}, \beta_{\text{Age[70-74]}}, \beta_{\text{Age[75-79]}}, \beta_{\text{Age[80-84]}}, \beta_{\text{Age[85+]}})$  
$\overrightarrow{\beta}_{\text{Race}} = (\beta_{\text{Asian}}, \beta_{\text{Black}}, \beta_{\text{Hispanic}}, \beta_{\text{PacificIslander}}, \beta_{\text{Unknown}})$  
$\overrightarrow{\beta}_{\text{College}} = (\beta_{\text{\% with College Degree Quartile 2}}, \beta_{\text{\% with College Degree Quartile 3}}, \beta_{\text{\% with College Degree Quartile 4}})$  
$\overrightarrow{\beta}_{\text{Insurance}} = (\beta_{\text{\% with Insurance Quartile 2}}, \beta_{\text{\% with Insurance Quartile 3}}, \beta_{\text{\% with Insurance Quartile 4}})$


For clarity the base terms ($\text{BaseTerms}_i$) are defined to be the terms present in all models:  
\begin{equation*}
  \label{eq:BaseTermsOSP}
  \begin{split}
    \text{BaseTerms}_i &= \beta_0 + \overrightarrow{\beta}_{\text{Age Group}}\overrightarrow{\text{Age Group}}_i + \beta_{\text{Sex}}\text{Sex}_i + \overrightarrow{\beta}_{\text{Race}}\overrightarrow{\text{Race}}_i\\
		&+ \overrightarrow{\beta}_{\text{College}}\overrightarrow{\text{\% with College Degree Quartile}}_i\\
		&+ \overrightarrow{\beta}_{\text{Insurance}}\overrightarrow{\text{\% with Medical Insurance Quartile}}_i \\
		&+ \beta_{\text{Population Density}}\text{Population Density}_i + \beta_{\text{Median Income}}\text{Median Income}_i,
	\end{split}
\end{equation*}

Model 0:
\begin{equation}
\label{eq:Model0OSP}
	\begin{split}
		\log(O_i) &= \text{BaseTerms}_i,
	\end{split}
\end{equation}
without a random intercept for zip code.

Model 1:
\begin{equation}
\label{eq:Model1OSP}
	\begin{split}
		\log(O_i) &= \text{BaseTerms}_i,
	\end{split}
\end{equation}
with a random intercept for zip code.

Model 2:
\begin{equation}
\label{eq:Model2OSP}
	\begin{split}
		\log(O_i) &= \text{BaseTerms}_i\\
		&+ \beta_{\text{Passive detection}}\text{\% of Zip Code SARS-CoV2+}_i,
	\end{split}
\end{equation}
without a random intercept for zip code.