---
title: "Complete analysis: Factors associated with morality among people diagnosed
  with COVID-19"
output: 
  pdf_document:
    extra_dependencies:
      amsmath 
params:
  reclean_data: FALSE
  first_test_date: "2020-03-01"
  last_test_date: "2020-08-16"
  refit_model1: FALSE
  refit_model2: FALSE
  refit_model3: FALSE
  refit_model4: FALSE
  refit_model5: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  message = FALSE, 
  error = FALSE,
  fig.pos = "H"
)
```


```{r loading-libraries}
# data-wrangling-function chunk
library(tidyverse)
library(here)
library(lubridate)
library(data.table)
# missing-data-table chunk
library(knitr)
library(kableExtra)
# fit-model1 chunk
library(tictoc)
library(lme4)
library(BRRR)
library(car) # I dont think I need this anymore
library(mgcv)
```


```{r data-wrangling-function}
read_pos_pcr <- function(file_path, start_date, end_date) {
  pos_results_original <- read_csv(
    file_path,
    col_types = cols(
      .default = col_skip(),
      Age = col_double(),
      Gender = col_character(),
      Ethnicity = col_character(),
      Race = col_character(),
      ReportedCity = col_character(),
      Zip = col_double(),
      SpCollDt = col_date(),
      DeathDueCOVID = col_character(),
      DtDeath = col_date(),
      unique_num = col_double()
    )
  ) 
  
  full_num_data_cases <- pos_results_original %>% 
    filter(SpCollDt >= ymd(start_date) & SpCollDt <= ymd(end_date)) %>% 
    nrow()

  
  pos_results_original$Race[is.na(pos_results_original$Race)] <- "Unknown"
  pos_results_original$Ethnicity[is.na(pos_results_original$Ethnicity)] <- "Unknown"

  hispanic_race_unknown <- (
    (pos_results_original$Race == "Other" & 
     pos_results_original$Ethnicity == "Hispanic or Latino") |
    (pos_results_original$Race == "Unknown" & 
     pos_results_original$Ethnicity == "Hispanic or Latino") |
    (pos_results_original$Race == "Multiple Races" & 
     pos_results_original$Ethnicity == "Hispanic or Latino") 
  )
  
  non_hispanic_unknown <- (
    (pos_results_original$Race == "Unknown" & 
     pos_results_original$Ethnicity != "Hispanic or Latino") |
    (pos_results_original$Race == "Multiple Races" & 
     pos_results_original$Ethnicity != "Hispanic or Latino")
  )
  
  pos_results_original_new_race <- data.frame(
    pos_results_original, 
    "race1" = str_to_lower(pos_results_original$Race)
  )
  
  pos_results_original_new_race$race1[hispanic_race_unknown] <- "hispanic or latino"
  pos_results_original_new_race$race1[non_hispanic_unknown] <- "unknown"
  
  
  pos_results_original_new_race$DeathDueCOVID <- replace_na(
    pos_results_original_new_race$DeathDueCOVID,
    "unknown"
  )
  pos_results_original_new_race$Age <- replace_na(
    pos_results_original_new_race$Age,
    -999
  )
  pos_results_original_new_race$Zip <- replace_na(
    pos_results_original_new_race$Zip,
    "unknown"
  )
  
  
  pos_results_adjusted <- pos_results_original_new_race %>% 
    mutate(death_due_to_covid = str_to_lower(DeathDueCOVID)) %>% 
    mutate(sex = fct_collapse(
      str_to_lower(Gender),
      male = "m",
      female = "f",
      unknown = c("o", "u")
    )) %>%
    mutate(race = factor(
      race1, 
      levels = c(
        "white",
        "asian",
        "black or african american",
        "hispanic or latino",
        "american indian or alaska native",
        "native hawaiian or other pacific islander",
        "other",
        "unknown"
      ),
    )) %>% 
    mutate(death_date = replace_na(DtDeath, ymd("9999/09/09"))) %>% 
    mutate(           # time_days = days from start date to date they tested positive
      time_days = as.integer(round(difftime(
        SpCollDt, 
        start_date, 
        units = "days"
      )))
    ) %>%
    select(
      unique_num,
      test_date = SpCollDt,
      death_date,
      death_due_to_covid,
      zip = Zip,
      time_days,
      age = Age,
      sex,
      race,
      reported_city = ReportedCity
    ) %>% 
    filter((test_date >= ymd(start_date)) & (test_date <= ymd(end_date))) %>% 
    filter(sex != "unknown") %>% 
    filter(age != -999) %>% 
    filter(zip != "unknown") %>% 
    mutate(zip = str_sub(zip, end = 5)) %>% 
    arrange(test_date) 
  
  
  # Add zip code level data and merge with pcr results
  zip_area_oc <- read_csv(
    here("data", "zip-area2.csv"),
    col_types = cols(
      .default = col_skip(),
      NAME = col_character(),
      Zip = col_character(),
      AreaKm = col_double()
    )
  ) %>%
    select(name = NAME, zip = Zip, area_km = AreaKm)
  
  zip_pop_oc <- read_csv(
    here("data", "zip-pop.csv"),
    col_types = cols(
      .default = col_skip(),
      Zip = col_character(),
      Population = col_integer()
    )
  ) %>%
    drop_na() %>%
    mutate(population = Population / 1000) %>%
    select(zip = Zip, population)
  
  zip_data_merged <- merge(x = zip_area_oc, y = zip_pop_oc, by = "zip")
  zip_data_merged$pop_density <- zip_data_merged$population / zip_data_merged$area_km
  
  zip_income_oc <- read_csv(
    here("data", "income-by-zip2.csv"),
    col_types = cols(
      .default = col_skip(),
      Zip = col_character(),
      IncomeMed = col_integer(),
      IncPeriodofMeas = col_character()
    )
  ) %>%
    mutate(med_income = IncomeMed / 10000) %>%
    filter(IncPeriodofMeas == "2014-2018") %>%
    select(zip = Zip, med_income)
  
  zip_data_merged <- merge(x = zip_data_merged, y = zip_income_oc, by = "zip")

  zip_education_oc <- read_csv(
    here("data", "education-by-zip.csv"),
    col_types = cols(
      .default = col_skip(),
      Zip = col_character(),
      PercentBach = col_double()
    )
  ) %>%
    select(zip = Zip, percent_bachelors = PercentBach)
  
  zip_data_merged <- merge(x = zip_data_merged, y = zip_education_oc, by = "zip")

  zip_insurance_oc <- read_csv(
    here("data", "insurance-by-zip.csv"),
    col_types = cols(
      .default = col_skip(),
      Zip = col_character(),
      PercentInsured = col_double()
    )
  ) %>%                           
    select(zip = Zip, percent_insured = PercentInsured)
  
  zip_data_merged <- merge(x = zip_data_merged, y = zip_insurance_oc, by = "zip")

  
  #3 rows in 92678 zipcode we don't have area data for
  pos_results_adjusted$old_zip <- pos_results_adjusted$zip
  pos_results_adjusted$zip[pos_results_adjusted$old_zip == "92678"] <- "92679"
  pos_results_merged <- merge(x = pos_results_adjusted, y = zip_data_merged, by = "zip")
  pos_results_merged$old_zip <- factor(pos_results_merged$old_zip)
  pos_results_merged$zip <- factor(pos_results_merged$zip)
  
  
  missing_vec <- c(
    full_num_data_cases , # number of observations with test date between start date and end date
    full_num_data_cases - nrow(pos_results_adjusted),  # number of NA for age, sex and zip
    nrow(pos_results_adjusted) - nrow(pos_results_merged) # number of invalid or non Orange County zip codes
  )
  names(missing_vec) <- c(
    "full_num_data_cases", 
    "num_na_cases_removed", 
    "num_bad_zip_cases_removed"
  )
  
  
  # Group and scale variables 
  age_breaks <- c(0, 5, 10, 15, 20, 25, 30, 35, 40, 50, 60, 70, 80, 200)
  age_labels <- c("0-4","5-9","10-14","15-19","20-24","25-29","30-34","35-39",
                  "40-49","50-59","60-69","70-79","80+")
  setDT(pos_results_merged)[, age_group := cut(
    age, 
    breaks = age_breaks, 
    right = FALSE, 
    labels = age_labels
    )]
  
  pos_results_merged$age_group <- factor(
    pos_results_merged$age_group,
    levels = age_labels
    )
  
  pos_results_merged$adj_time_days <- scale(
    pos_results_merged$time_days,
    center = TRUE,
    scale = TRUE
    )
  
  pos_results_merged$adj_pop_density <- scale(
    pos_results_merged$pop_density, 
    center = TRUE, 
    scale = TRUE
    )
  
  pos_results_merged$adj_med_income <- scale(
    pos_results_merged$med_income, 
    center = TRUE, 
    scale = TRUE
    )
  
  pos_results_merged$adj_perc_bach <- scale(
    pos_results_merged$percent_bachelors,
    center = TRUE,
    scale = TRUE
    )
  
  pos_results_merged$adj_perc_bach_quar <- with(
    pos_results_merged,
    cut(adj_perc_bach,
        breaks = quantile(adj_perc_bach, 
        probs = seq(0, 1, by = 0.25)),
        include.lowest = TRUE,
        labels = c("Q1", "Q2", "Q3", "Q4"))
    )
  
  pos_results_merged$adj_perc_insured <- scale(
    pos_results_merged$percent_insured,
    center = TRUE,
    scale = TRUE
    )
  
  pos_results_merged$adj_perc_insured_quar <- with(
    pos_results_merged,
    cut(
      adj_perc_insured,
      breaks = quantile(adj_perc_insured, probs = seq(0, 1, by = 0.25)),
      include.lowest = TRUE,
      labels = c("Q1", "Q2", "Q3", "Q4")
      )
    )
  
  
  list(
    "pos_results_merged" = pos_results_merged, 
    "zip_data_merged" = zip_data_merged, 
    "missing" = missing_vec
  )
}

```


```{r load-clean-data}
if (params$reclean_data) {
  pos_pcr_and_zip <- read_pos_pcr(
    file_path = here("data", "all-positive-tests-update-2020-11-09.csv"),
    start_date = params$first_test_date,
    end_date = params$last_test_date
  )
  
  pos_pcr <- data.frame(pos_pcr_and_zip[["pos_results_merged"]])
  pos_zip <- data.frame(pos_pcr_and_zip[["zip_data_merged"]])
  pos_counts <- pos_pcr_and_zip[["counts"]]
  save(pos_pcr_and_zip, file = here("data", "cleaned_process_pos_pcr_data.Rdata"))
} else {
  load(file = here("data", "cleaned_process_pos_pcr_data.Rdata"))
  
  pos_pcr <- data.frame(pos_pcr_and_zip[["pos_results_merged"]])
  pos_zip <- data.frame(pos_pcr_and_zip[["zip_data_merged"]])
  pos_missing <- pos_pcr_and_zip[["missing"]]
}
```


```{r missing-data-table}
usable_counts <- c(
  pos_missing[1],
  pos_missing[1] - pos_missing[2],
  pos_missing[1] - sum(pos_missing[2:3])
)

tab_obs <- data.frame(
  c(NA, pos_missing[2:3]), 
  usable_counts
)
rownames(tab_obs) <- c(
  "Unmodified",
  "Missing or Inconclusive[note]",
  "Invalid Zip Code"
)

kable(
  tab_obs,
  col.names = c(
    "With Issue", 
    "After Removal"
  ),
  format = "latex",
  caption = paste(
    "Number of COVID-19 tests and unique individuals who tested in Orange County from ",
      params$first_test_date, " to ", params$last_test_date,
      ". Includes number removed from data by type of issue for this analysis.",
    sep = "")
  ) %>%
  kable_styling(latex_options = c("HOLD_position")) %>% 
  add_header_above(c(" " = 1, "Number of Tests" = 2), line = FALSE) %>% 
  add_footnote(
    c(
      "Number without conclusive test result or complete demographic information"
      ),
    notation = "symbol"
    )
```



