---
title: "Positivity Modeling"
author: "Christie Yang"
date: "5/20/2022"
output: html_document
---

## Positivity Data Modeling

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(dplyr)
library(here)
library(tictoc)
library(beepr)
library(splines)


# Positivity Data
load(here("data/cleaned-data", "usable_tests.Rdata"))
head(usable_tests)

```

```{r}
tic()
model_0 <- glmer(
  formula = covid_positive ~ age_group + sex + race + 
            adj_perc_bach_quar + adj_perc_insured_quar +
            adj_pop_density + adj_med_income +
            adj_time_days +
            (1 | zip),              
  family = binomial, 
  data = usable_tests,
  control = glmerControl(optimizer ="bobyqa", optCtrl = list(maxfun = 2e6))
  )
toc()
beep()
```

```{r}
tic()
fit_time_quad <- glmer(
  formula = covid_positive ~ age_group + sex + race + 
            adj_perc_bach_quar + adj_perc_insured_quar +
            adj_pop_density + adj_med_income +
            I(adj_time_days) + I(adj_time_days^2) + 
            (1 | zip),              
  family = binomial, 
  data = usable_tests,
  control = glmerControl(optimizer ="bobyqa", optCtrl = list(maxfun = 2e6))
  )
toc()
beep()
```

```{r}

```



